config/routes.rb
Rails.application.routes.draw do
  # GET /about
  get "about", to: "about#index"

  get "/", to: "main#index"

  root to: "player#main"
  get "player", to: "main#player"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def player
  end
end

app/controllers/player_controller.rb
class PlayerController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>about this game</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpaceInvadersStarWars</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_importmap_tags %>

  </head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<%= stylesheet_link_tag("index")%>
<header>
   <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
</header>

 <%= link_to "Start",player_path, class: "btn" %>
<span class="btn-blick">
</span>



<%= image_tag "sound.jpg", class: "sound" %>


<%= video_tag "Spaceship.mp4", autoplay: :autoplay, loop: :loop, muted: :muted,  class: "home_video" %>

<div class="intro">
 <audio src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/244725/MainTitle.ogg" onloadeddata="var audioPlayer = this; setTimeout(function(){ audioPlayer.play(); }, 4500)">
</audio>

<section class="star-wars">
  <div class="crawl">
    <div class="title">
      <h1><a target="_top"><img src="https://blog.flamingtext.com/blog/2022/12/20/flamingtext_com_1671566383_557787540.png" border="0" ></a>
</h1>


<p>We need you !!! </p>

<p>It is a period of civil war.
Rebel spaceships, striking
from a hidden base, have won
their first victory against
the evil Galactic Empire. </p>

<p>During the battle, Rebel
spies managed to steal secret
plans to the Empire's
ultimate weapon, the DEATH
STAR, an armored space
station with enough power to
destroy an entire planet.</p>

<p>Pursued by the Empire's
sinister agents, Princess
Leia races home aboard her
starship, custodian of the
stolen plans that can save
her people and restore
freedom to the galaxy....</p>


</div>
</section>

app/views/main/player.html.erb
<div class="canvas" data-controller="player">
<canvas></canvas>
<script src="./player_controller.js"></script>
</div>